Fixed issues reported by checkstyle related to utility class and missing end of file
fjcoding/AT13 pull request #9
Opened 2021-02-01 22:37 UTC by J0c4

Also, removed some checks due those are not going to be needed by this
project: javadocs, star import

2021-02-01 22:41 UTC, SaulCM approved these changes

2021-02-01 22:42 UTC, JessickaMoya approved these changes

2021-02-02 03:18 UTC, SaulCM requested changes

2021-02-02 03:18 UTC, SaulCM commented on config/checkstyle/checkstyle.xml
> +    <module name="MissingJavadocMethod"/>-->
Miss "<!--" at the beginning in order to comment line.

2021-02-02 03:28 UTC, SaulCM approved these changes

2021-02-02 03:35 UTC, merged